package com.flowtrans.core

import com.flowtrans.data.DnsMode
import com.flowtrans.data.Protocol
import com.flowtrans.data.ProxyProfile
import com.flowtrans.data.RoutingMode

/**
 * Renders a mihomo (Clash.Meta) config.yaml that forwards tunnel traffic to a single
 * upstream proxy (the mitmproxy instance described by [ProxyProfile]).
 *
 * Note: the TUN inbound is NOT declared here — the vendored core sets it up directly from
 * the VpnService fd via Bridge.startTun(fd, stack, gateway, portal, dns). This file only
 * defines outbound + DNS + rules.
 */
object ConfigBuilder {
    private const val UPSTREAM = "upstream"
    private const val GROUP = "PROXY"

    fun build(
        profile: ProxyProfile,
        routingMode: RoutingMode,
        dnsMode: DnsMode,
        extraRules: List<String> = emptyList(),
    ): String {
        val sb = StringBuilder()
        sb.appendLine("# Generated by FlowTrans")
        // No mixed-port inbound: the TUN inbound is provided programmatically via
        // Bridge.startTun(fd, ...), so a listener port would only cause conflicts.
        sb.appendLine("allow-lan: false")
        sb.appendLine("mode: rule")
        sb.appendLine("log-level: info")
        sb.appendLine("ipv6: false")
        sb.appendLine("unified-delay: true")
        sb.appendLine()

        appendDns(sb, dnsMode, profile.host)
        appendSniffer(sb)
        appendProxies(sb, profile)
        appendProxyGroups(sb)
        appendRules(sb, routingMode, extraRules)

        return sb.toString()
    }

    private fun appendDns(sb: StringBuilder, dnsMode: DnsMode, upstreamHost: String) {
        sb.appendLine("dns:")
        sb.appendLine("  enable: true")
        sb.appendLine("  listen: 0.0.0.0:1053")
        sb.appendLine("  ipv6: false")
        sb.appendLine("  enhanced-mode: ${dnsMode.yaml}")
        if (dnsMode == DnsMode.FAKE_IP) {
            sb.appendLine("  fake-ip-range: 198.18.0.1/16")
            sb.appendLine("  fake-ip-filter:")
            sb.appendLine("    - \"*.lan\"")
            sb.appendLine("    - \"+.local\"")
            // Never fake-ip the upstream proxy host itself.
            sb.appendLine("    - ${yaml(upstreamHost)}")
        }
        sb.appendLine("  default-nameserver:")
        sb.appendLine("    - 223.5.5.5")
        sb.appendLine("    - 8.8.8.8")
        sb.appendLine("  nameserver:")
        sb.appendLine("    - 223.5.5.5")
        sb.appendLine("    - 8.8.8.8")
        sb.appendLine()
    }

    private fun appendSniffer(sb: StringBuilder) {
        // Recover real hostnames (SNI/Host) so mitmproxy sees domains even for IP-literal flows.
        sb.appendLine("sniffer:")
        sb.appendLine("  enable: true")
        sb.appendLine("  parse-pure-ip: true")
        sb.appendLine("  override-destination: false")
        sb.appendLine("  sniff:")
        sb.appendLine("    HTTP:")
        sb.appendLine("      ports: [80, 8080-8880]")
        sb.appendLine("    TLS:")
        sb.appendLine("      ports: [443, 8443]")
        sb.appendLine("    QUIC:")
        sb.appendLine("      ports: [443, 8443]")
        sb.appendLine()
    }

    private fun appendProxies(sb: StringBuilder, p: ProxyProfile) {
        sb.appendLine("proxies:")
        sb.appendLine("  - name: ${yaml(UPSTREAM)}")
        when (p.protocol) {
            Protocol.HTTP, Protocol.HTTPS -> {
                sb.appendLine("    type: http")
                sb.appendLine("    server: ${yaml(p.host)}")
                sb.appendLine("    port: ${p.port}")
                appendAuth(sb, p)
                val tls = p.protocol == Protocol.HTTPS || p.tls
                if (tls) {
                    sb.appendLine("    tls: true")
                    p.sni?.takeIf { it.isNotBlank() }?.let { sb.appendLine("    sni: ${yaml(it)}") }
                    sb.appendLine("    skip-cert-verify: ${p.skipCertVerify}")
                }
            }
            Protocol.SOCKS5 -> {
                sb.appendLine("    type: socks5")
                sb.appendLine("    server: ${yaml(p.host)}")
                sb.appendLine("    port: ${p.port}")
                appendAuth(sb, p)
                sb.appendLine("    udp: ${p.udp}")
                if (p.tls) {
                    sb.appendLine("    tls: true")
                    p.sni?.takeIf { it.isNotBlank() }?.let { sb.appendLine("    sni: ${yaml(it)}") }
                    sb.appendLine("    skip-cert-verify: ${p.skipCertVerify}")
                }
            }
        }
        sb.appendLine()
    }

    private fun appendAuth(sb: StringBuilder, p: ProxyProfile) {
        val u = p.username?.takeIf { it.isNotBlank() } ?: return
        sb.appendLine("    username: ${yaml(u)}")
        sb.appendLine("    password: ${yaml(p.password ?: "")}")
    }

    private fun appendProxyGroups(sb: StringBuilder) {
        sb.appendLine("proxy-groups:")
        sb.appendLine("  - name: ${yaml(GROUP)}")
        sb.appendLine("    type: select")
        sb.appendLine("    proxies:")
        sb.appendLine("      - $UPSTREAM")
        sb.appendLine("      - DIRECT")
        sb.appendLine()
    }

    private fun appendRules(sb: StringBuilder, routingMode: RoutingMode, extraRules: List<String>) {
        sb.appendLine("rules:")
        // Custom domain rules take precedence (used for rule-based routing on top of per-app).
        extraRules.forEach { sb.appendLine("  - $it") }
        // In both GLOBAL and PER_APP modes, everything that ENTERS the tunnel is forwarded.
        // Per-app scoping is enforced by the VpnService allow-list, not by rules.
        sb.appendLine("  - MATCH,$GROUP")
    }

    /** Minimal YAML string quoting: always double-quote and escape backslash/quote. */
    private fun yaml(s: String): String {
        val escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }
}
